import subprocess
import sys
import shutil
import tempfile
from pathlib import Path


def write_build_info(base_dir: Path):
    """Write build metadata so frozen binaries can report their source commit."""
    output_path = base_dir / "core" / "_generated_build_info.py"

    commit = ""
    dirty = False
    try:
        commit = subprocess.check_output(
            ["git", "rev-parse", "--short=12", "HEAD"],
            cwd=base_dir,
            stderr=subprocess.DEVNULL,
            text=True,
        ).strip()
        dirty = bool(
            subprocess.check_output(
                ["git", "status", "--porcelain"],
                cwd=base_dir,
                stderr=subprocess.DEVNULL,
                text=True,
            ).strip()
        )
    except (FileNotFoundError, subprocess.CalledProcessError):
        pass

    content = (
        '"""Auto-generated by build_exe.py."""\n'
        f"BUILD_COMMIT = {commit!r}\n"
        f"BUILD_DIRTY = {dirty!r}\n"
    )
    output_path.write_text(content)

def build():
    """Build the Prism Desktop executable."""
    print("Building Prism Desktop...")

    # Define paths
    base_dir = Path(__file__).parent
    dist_dir = base_dir / "dist"
    build_dir = base_dir / "build"
    icon_path = base_dir / "icon.png"
    font_path = base_dir / "materialdesignicons-webfont.ttf"
    
    # Clean previous builds
    if dist_dir.exists():
        shutil.rmtree(dist_dir)
    if build_dir.exists():
        shutil.rmtree(build_dir)
        
    # Build command
    cmd = [
        sys.executable, "-m", "PyInstaller",
        "--noconsole",
        "--onefile",
        "--name", "PrismDesktop",
        "--add-data", f"{font_path};.",  # Windows separator is ;
        "--exclude", "PySide6",  # Avoid Qt binding conflict
    ]
    
    # Add icon if exists — Windows needs .ico, so convert from .png via Pillow
    ico_tmp = None
    if icon_path.exists():
        if sys.platform == "win32" and icon_path.suffix.lower() == ".png":
            try:
                from PIL import Image
                tmp = tempfile.NamedTemporaryFile(suffix=".ico", delete=False)
                tmp.close()
                ico_tmp = Path(tmp.name)
                img = Image.open(icon_path)
                img.save(ico_tmp, format="ICO", sizes=[(256, 256), (128, 128), (64, 64), (48, 48), (32, 32), (16, 16)])
                cmd.extend(["--icon", str(ico_tmp)])
            except ImportError:
                print("Warning: Pillow not installed — skipping icon. Run: pip install pillow")
        else:
            cmd.extend(["--icon", str(icon_path)])
        
    # Add cached mapping if exists
    mapping_path = base_dir / "mdi_mapping.json"
    if mapping_path.exists():
        cmd.extend(["--add-data", f"{mapping_path};."])

    # Add translations folder
    translations_path = base_dir / "translations"
    if translations_path.exists():
        cmd.extend(["--add-data", f"{translations_path};translations"])

    write_build_info(base_dir)
        
    # Main script
    cmd.append("main.py")
    
    print(f"Running: {' '.join(str(x) for x in cmd)}")
    
    try:
        subprocess.check_call(cmd, cwd=base_dir)
    finally:
        if ico_tmp and ico_tmp.exists():
            ico_tmp.unlink()

    print("\nBuild complete!")
    print(f"Executable is at: {dist_dir / 'PrismDesktop.exe'}")
    print("Note: Configuration is stored in %APPDATA%/PrismDesktop/config.json")

if __name__ == "__main__":
    build()
